### PR TITLE
New option for skip progress dots

### PR DESCRIPTION
**Pull request by bckp**
On some CI systems, there is problem with progress bars, so this add
option, to not show the progress dots at all.

### CODE REVIEW

**Comment by bckp** [comment]
Should I remove -n option and leave only --no-progress or is this ok for you @dg

**Comment by dg** [comment]
Only `--no-progress` seems better.

**Comment by bckp** [comment]
Changed

**Comment by bckp** [comment]
Fixed missing space before bracket, should be ready to merge @dg

**Comment by dg** [comment]
Can you change noProgress to showProgress?

**Comment by bckp** [comment]
So progress will be off by default, and on `--show-progress` will be shown @dg ?

**Comment by JanTvrdik** [comment]
@bckp I think he meant renaming just the property, the name of the option would remain. But I could be wrong.

**Comment by dg** [comment]
Thanks!

**Pull request merged**
